# Generated by Django 6.0.1 on 2026-01-12 11:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diabetic_values', models.JSONField(default=dict)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/pdfs/')),
                ('ai_summary_text', models.TextField(blank=True, default='')),
                ('ai_raw', models.JSONField(blank=True, default=dict)),
                ('openai_response_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(default='created', max_length=32)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
