# Generated by Django 5.2.7 on 2026-01-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pdf_file',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
