# Generated by Django 5.2.7 on 2026-01-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Only active prompts will be appended.')),
                ('custom_instructions', models.TextField(help_text='Custom instructions to append to the system prompt.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Prompts',
                'ordering': ['-updated_at'],
            },
        ),
    ]
