# Generated by Django 6.0.1 on 2026-01-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_adminprompt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprompt',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Admin Prompt', 'verbose_name_plural': 'Admin Prompts'},
        ),
    ]
